# Site settings
name: Bluebell3310's Blog
email: samabc75@gmail.com
author: Sam Yang
url: https://bluebell3310.github.io/resume/index.html
resume_site: https://bluebell3310.github.io/resume/index.html
github: https://github.com/bluebell3310/
baseurl: ""
description: 一個大學生的部落格
meta_description: bluebell3310的個人部落格-只要睡飽，都是好天氣
motto: 你必須更加努力，才能看起來更加費力
banner: 只要睡飽，都是好天氣

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bluebell3310
